import React, { PureComponent } from "react";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

const data = [
  {
    Index: 340,
    Entity: "Yahoo",
    Year: 2013,
    Records: 3000000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 118,
    Entity: "First American Corporation",
    Year: 2019,
    Records: 885000000,
    "Organization type": "financial service company",
    "Method\r": "poor security\r",
  },
  {
    Index: 112,
    Entity: "Facebook",
    Year: 2019,
    Records: 540000000,
    "Organization type": "social network",
    "Method\r": "poor security\r",
  },
  {
    Index: 176,
    Entity: "Marriott International",
    Year: 2018,
    Records: 500000000,
    "Organization type": "hotel",
    "Method\r": "hacked\r",
  },
  {
    Index: 341,
    Entity: "Yahoo",
    Year: 2014,
    Records: 500000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 121,
    Entity: "Friend Finder Networks",
    Year: 2016,
    Records: 412214295,
    "Organization type": "web",
    "Method\r": "poor security / hacked\r",
  },
  {
    Index: 106,
    Entity: "Exactis",
    Year: 2018,
    Records: 340000000,
    "Organization type": "data broker",
    "Method\r": "poor security\r",
  },
  {
    Index: 8,
    Entity: "Airtel",
    Year: 2019,
    Records: 320000000,
    "Organization type": "telecommunications",
    "Method\r": "poor security\r",
  },
  {
    Index: 285,
    Entity: "Truecaller",
    Year: 2019,
    Records: 299055000,
    "Organization type": "Telephone directory",
    "Method\r": "unknown\r",
  },
  {
    Index: 191,
    Entity: "MongoDB",
    Year: 2019,
    Records: 275000000,
    "Organization type": "tech",
    "Method\r": "poor security\r",
  },
  {
    Index: 331,
    Entity: "Wattpad",
    Year: 2020,
    Records: 270000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 114,
    Entity: "Facebook",
    Year: 2019,
    Records: 267000000,
    "Organization type": "social network",
    "Method\r": "poor security\r",
  },
  {
    Index: 184,
    Entity: "Microsoft",
    Year: 2019,
    Records: 250000000,
    "Organization type": "tech",
    "Method\r": "data exposed by misconfiguration\r",
  },
  {
    Index: 190,
    Entity: "MongoDB",
    Year: 2019,
    Records: 202000000,
    "Organization type": "tech",
    "Method\r": "poor security\r",
  },
  {
    Index: 124,
    Entity: "Unknown",
    Year: 2020,
    Records: 201000000,
    "Organization type":
      "personal and demographic data about residents and their properties of US",
    "Method\r": "Poor security\r",
  },
  {
    Index: 149,
    Entity: "Instagram",
    Year: 2020,
    Records: 200000000,
    "Organization type": "social network",
    "Method\r": "poor security\r",
  },
  {
    Index: 347,
    Entity: "Zynga",
    Year: 2019,
    Records: 173000000,
    "Organization type": "social network",
    "Method\r": "hacked\r",
  },
  {
    Index: 103,
    Entity: "Equifax",
    Year: 2017,
    Records: 163119000,
    "Organization type": "financial, credit reporting",
    "Method\r": "poor security\r",
  },
  {
    Index: 92,
    Entity: "Dubsmash",
    Year: 2018,
    Records: 162000000,
    "Organization type": "messaging app",
    "Method\r": "hacked\r",
  },
  {
    Index: 179,
    Entity: "Massive American business hack including 7-Eleven and Nasdaq",
    Year: 2012,
    Records: 160000000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 3,
    Entity: "Adobe Systems Incorporated",
    Year: 2013,
    Records: 152000000,
    "Organization type": "tech",
    "Method\r": "hacked\r",
  },
  {
    Index: 301,
    Entity: "Under Armour",
    Year: 2018,
    Records: 150000000,
    "Organization type": "Consumer Goods",
    "Method\r": "hacked\r",
  },
  {
    Index: 95,
    Entity: "eBay",
    Year: 2014,
    Records: 145000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 50,
    Entity: "Canva",
    Year: 2019,
    Records: 140000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 141,
    Entity: "Heartland",
    Year: 2009,
    Records: 130000000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 275,
    Entity: "Tetrad",
    Year: 2020,
    Records: 120000000,
    "Organization type": "market analysis",
    "Method\r": "poor security\r",
  },
  {
    Index: 270,
    Entity: "Target Corporation",
    Year: 2013,
    Records: 110000000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 99,
    Entity: "ElasticSearch",
    Year: 2019,
    Records: 108000000,
    "Organization type": "tech",
    "Method\r": "poor security\r",
  },
  {
    Index: 52,
    Entity: "Capital One",
    Year: 2019,
    Records: 106000000,
    "Organization type": "financial",
    "Method\r": "unsecured S3 bucket\r",
  },
  {
    Index: 159,
    Entity: "Justdial",
    Year: 2019,
    Records: 100000000,
    "Organization type": "local search",
    "Method\r": "unprotected api\r",
  },
  {
    Index: 192,
    Entity: "Mobile TeleSystems (MTS)",
    Year: 2019,
    Records: 100000000,
    "Organization type": "telecommunications",
    "Method\r": "misconfiguration/poor security\r",
  },
  {
    Index: 228,
    Entity: "Quora",
    Year: 2018,
    Records: 100000000,
    "Organization type": "Question & Answer",
    "Method\r": "hacked\r",
  },
  {
    Index: 230,
    Entity: "Rambler.ru",
    Year: 2012,
    Records: 98167935,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 280,
    Entity: "TK / TJ Maxx",
    Year: 2007,
    Records: 94000000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 197,
    Entity: "MyHeritage",
    Year: 2018,
    Records: 92283889,
    "Organization type": "genealogy",
    "Method\r": "unknown\r",
  },
  {
    Index: 16,
    Entity: "AOL",
    Year: 2004,
    Records: 92000000,
    "Organization type": "web",
    "Method\r":
      'inside job, hacked"\r\n15,Anthem Inc.,2015,80000000,healthcare,hacked\r\n252,Sony PlayStation Network,2011,77000000,gaming,hacked\r\n158,JP Morgan Chase,2014,76000000,financial,hacked\r\n317,National Archives and Records Administration (U.S. military veterans records),2009,76000000,military,lost / stolen media\r\n89,Dropbox,2012,68648009,web,hacked\r\n287,Tumblr,2013,65469298,web,hacked\r\n309,United States Postal Service,2018,60000000,government,poor security\r\n293,Uber,2017,57000000,transport,hacked\r\n59,CheckPeople,2020,56000000,background check,unknown\r\n145,Home Depot,2014,56000000,retail,hacked\r\n69,Philippines Commission on Elections,2016,55000000,government,hacked\r\n105,Evernote,2013,50000000,web,hacked\r\n111,Facebook,2018,50000000,social network,poor security\r\n173,Living Social,2013,50000000,web,hacked\r\n13,Animal Jam,2020,46000000,gaming,hacked\r\n282,T-Mobile,2021,45000000,telecom,hacked\r\n333,Weebly,2016,43430316,web,hacked\r\n279,TikTok,2020,42000000,social media,poor security\r\n53,"CardSystems Solutions Inc. (MasterCard, Visa, Discover Financial Services and American Express)',
  },
  {
    Index: 322,
    Entity: "View Media",
    Year: 2020,
    Records: 38000000,
    "Organization type": "online marketing",
    "Method\r": "publicly accessible Amazon Web Services (AWS) server\r",
  },
  {
    Index: 37,
    Entity: "Benesse",
    Year: 2014,
    Records: 35040000,
    "Organization type": "educational services",
    "Method\r": "hacked\r",
  },
  {
    Index: 262,
    Entity: "Steam",
    Year: 2011,
    Records: 35000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 22,
    Entity: "Ashley Madison",
    Year: 2015,
    Records: 32000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 234,
    Entity: "RockYou!",
    Year: 2009,
    Records: 32000000,
    "Organization type": "web, gaming",
    "Method\r": "hacked\r",
  },
  {
    Index: 332,
    Entity: "Wawa (company)",
    Year: 2020,
    Records: 30000000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 269,
    Entity: "Taringa!",
    Year: 2017,
    Records: 28722877,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 136,
    Entity: "HauteLook",
    Year: 2018,
    Records: 28517244,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 278,
    Entity: "Tianya Club",
    Year: 2011,
    Records: 28000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 314,
    Entity: "U.S. Department of Veteran Affairs",
    Year: 2006,
    Records: 26500000,
    "Organization type": "government, military",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 277,
    Entity: "Ticketfly (subsidiary of Eventbrite)",
    Year: 2018,
    Records: 26151608,
    "Organization type": "ticket distribution",
    "Method\r": "hacked\r",
  },
  {
    Index: 299,
    Entity: "UK Revenue & Customs",
    Year: 2007,
    Records: 25000000,
    "Organization type": "government",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 249,
    Entity: "Sony Online Entertainment",
    Year: 2011,
    Records: 24600000,
    "Organization type": "gaming",
    "Method\r": "hacked\r",
  },
  {
    Index: 346,
    Entity: "Zappos",
    Year: 2012,
    Records: 24000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 342,
    Entity: "Yahoo Japan",
    Year: 2013,
    Records: 22000000,
    "Organization type": "tech, web",
    "Method\r": "hacked\r",
  },
  {
    Index: 216,
    Entity: "US Office of Personnel Management",
    Year: 2015,
    Records: 21500000,
    "Organization type": "government",
    "Method\r": "hacked\r",
  },
  {
    Index: 223,
    Entity: "PayPay",
    Year: 2020,
    Records: 20076016,
    "Organization type": "QR code payment",
    "Method\r":
      'improper setting, hacked"\r\n17,AOL,2006,20000000,web,accidentally published\r\n164,Korea Credit Bureau,2014,20000000,financial,inside job\r\n268,Taobao,2016,20000000,retail,hacked\r\n26,Auction.co.kr,2008,18000000,web,hacked\r\n281,"T-Mobile, Deutsche Telekom',
  },
  {
    Index: 108,
    Entity: "Experian - T-Mobile US",
    Year: 2015,
    Records: 15000000,
    "Organization type": "telecoms",
    "Method\r": "hacked\r",
  },
  {
    Index: 170,
    Entity: "LifeLabs",
    Year: 2019,
    Records: 15000000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 1,
    Entity: "500px",
    Year: 2020,
    Records: 14870304,
    "Organization type": "social networking",
    "Method\r": "hacked\r",
  },
  {
    Index: 43,
    Entity: "Blizzard Entertainment",
    Year: 2012,
    Records: 14000000,
    "Organization type": "gaming",
    "Method\r": "hacked\r",
  },
  {
    Index: 207,
    Entity: "Nexon Korea Corp",
    Year: 2011,
    Records: 13200000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 32,
    Entity: "The Bank of New York Mellon",
    Year: 2008,
    Records: 12500000,
    "Organization type": "financial",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 19,
    Entity: "Apple, Inc./BlueToad",
    Year: 2021,
    Records: 12367232,
    "Organization type": "tech, retail",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 227,
    Entity: "Quest Diagnostics",
    Year: 2019,
    Records: 11900000,
    "Organization type": "Clinical Laboratory",
    "Method\r": "poor security\r",
  },
  {
    Index: 133,
    Entity: "GS Caltex",
    Year: 2008,
    Records: 11100000,
    "Organization type": "energy",
    "Method\r": "inside job\r",
  },
  {
    Index: 225,
    Entity: "Premera",
    Year: 2015,
    Records: 11000000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 61,
    Entity: "Chinese gaming websites (three: Duowan, 7K7K, 178.com)",
    Year: 2011,
    Records: 10000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 107,
    Entity: "Excellus BlueCross BlueShield",
    Year: 2015,
    Records: 10000000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 85,
    Entity: "Desjardins",
    Year: 2019,
    Records: 9700000,
    "Organization type": "financial",
    "Method\r": "inside job\r",
  },
  {
    Index: 54,
    Entity: "Cathay Pacific Airways",
    Year: 2018,
    Records: 9400000,
    "Organization type": "transport",
    "Method\r": "hacked\r",
  },
  {
    Index: 131,
    Entity: "Greek government",
    Year: 2012,
    Records: 9000000,
    "Organization type": "government",
    "Method\r": "hacked\r",
  },
  {
    Index: 166,
    Entity: "KT Corporation",
    Year: 2012,
    Records: 8700000,
    "Organization type": "telecoms",
    "Method\r": "hacked\r",
  },
  {
    Index: 78,
    Entity: "Dai Nippon Printing",
    Year: 2007,
    Records: 8637405,
    "Organization type": "retail",
    "Method\r": "inside job\r",
  },
  {
    Index: 117,
    Entity: "Fidelity National Information Services",
    Year: 2007,
    Records: 8500000,
    "Organization type": "financial",
    "Method\r": "inside job\r",
  },
  {
    Index: 208,
    Entity: "NHS",
    Year: 2011,
    Records: 8300000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 324,
    Entity: "Virginia Department of Health",
    Year: 2009,
    Records: 8257378,
    "Organization type": "government, healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 79,
    Entity:
      "Data Processors International (MasterCard, Visa, Discover Financial Services and American Express)",
    Year: 2008,
    Records: 8000000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 125,
    Entity: "Gamigo",
    Year: 2012,
    Records: 8000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 172,
    Entity: "LinkedIn, eHarmony, Last.fm",
    Year: 2012,
    Records: 8000000,
    "Organization type": "web",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 42,
    Entity: "Blank Media Games",
    Year: 2018,
    Records: 7633234,
    "Organization type": "gaming",
    "Method\r": "hacked\r",
  },
  {
    Index: 4,
    Entity: "Adobe Inc.",
    Year: 2019,
    Records: 7500000,
    "Organization type": "tech",
    "Method\r": "poor security\r",
  },
  {
    Index: 128,
    Entity: "Global Payments",
    Year: 2012,
    Records: 7000000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 263,
    Entity: "StockX",
    Year: 2019,
    Records: 6800000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 217,
    Entity: "Office of the Texas Attorney General",
    Year: 2012,
    Records: 6500000,
    "Organization type": "government",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 254,
    Entity: "South Carolina Government",
    Year: 2012,
    Records: 6400000,
    "Organization type": "healthcare",
    "Method\r": "inside job\r",
  },
  {
    Index: 350,
    Entity: "50 companies and government institutions",
    Year: 2022,
    Records: 6400000,
    "Organization type": "various",
    "Method\r": "poor security\r",
  },
  {
    Index: 272,
    Entity: "TD Ameritrade",
    Year: 2007,
    Records: 6300000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 339,
    Entity: "Xat.com",
    Year: 2015,
    Records: 6054459,
    "Organization type": "web",
    "Method\r": "social engineering\r",
  },
  {
    Index: 60,
    Entity: "China Software Developer Network",
    Year: 2011,
    Records: 6000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 110,
    Entity: "Facebook",
    Year: 2013,
    Records: 6000000,
    "Organization type": "social network",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 187,
    Entity: "Ministry of Education (Chile)",
    Year: 2008,
    Records: 6000000,
    "Organization type": "government",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 177,
    Entity: "Marriott International",
    Year: 2020,
    Records: 5200000,
    "Organization type": "hotel",
    "Method\r": "poor security/inside job\r",
  },
  {
    Index: 58,
    Entity: "CheckFree Corporation",
    Year: 2009,
    Records: 5000000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 129,
    Entity: "Gmail",
    Year: 2014,
    Records: 5000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 327,
    Entity: "VTech",
    Year: 2015,
    Records: 5000000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 283,
    Entity: "Tricare",
    Year: 2011,
    Records: 4901432,
    "Organization type": "military, healthcare",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 87,
    Entity: "DoorDash",
    Year: 2019,
    Records: 4900000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 247,
    Entity: "SnapChat",
    Year: 2013,
    Records: 4700000,
    "Organization type": "web, tech",
    "Method\r": "hacked\r",
  },
  {
    Index: 238,
    Entity: "Scottrade",
    Year: 2015,
    Records: 4600000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 68,
    Entity: "Community Health Systems",
    Year: 2014,
    Records: 4500000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 296,
    Entity: "UCLA Medical Center, Santa Monica",
    Year: 2015,
    Records: 4500000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 266,
    Entity: "Sutter Medical Center",
    Year: 2011,
    Records: 4243434,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 135,
    Entity: "Hannaford Brothers Supermarket Chain",
    Year: 2007,
    Records: 4200000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 5,
    Entity: "Advocate Medical Group",
    Year: 2017,
    Records: 4000000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 160,
    Entity: "KDDI",
    Year: 2006,
    Records: 4000000,
    "Organization type": "telecoms",
    "Method\r": "hacked\r",
  },
  {
    Index: 345,
    Entity: "YouTube",
    Year: 2020,
    Records: 4000000,
    "Organization type": "social media",
    "Method\r": "poor security\r",
  },
  {
    Index: 213,
    Entity: "Norwegian Tax Administration",
    Year: 2008,
    Records: 3950000,
    "Organization type": "government",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 62,
    Entity: "Citigroup",
    Year: 2005,
    Records: 3900000,
    "Organization type": "financial",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 181,
    Entity: "Medical Informatics Engineering",
    Year: 2015,
    Records: 3900000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 261,
    Entity: "State of Texas",
    Year: 2011,
    Records: 3500000,
    "Organization type": "government",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 97,
    Entity: "Educational Credit Management Corporation",
    Year: 2010,
    Records: 3300000,
    "Organization type": "financial",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 88,
    Entity: "UK Driving Standards Agency",
    Year: 2007,
    Records: 3000000,
    "Organization type": "government",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 153,
    Entity: "Iranian banks (three: Saderat, Eghtesad Novin, and Saman)",
    Year: 2012,
    Records: 3000000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 183,
    Entity: "Michaels",
    Year: 2014,
    Records: 3000000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 71,
    Entity: "Countrywide Financial Corp",
    Year: 2006,
    Records: 2600000,
    "Organization type": "financial",
    "Method\r": "inside job\r",
  },
  {
    Index: 157,
    Entity: "JP Morgan Chase",
    Year: 2010,
    Records: 2600000,
    "Organization type": "financial",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 72,
    Entity: "Countrywide Financial Corp",
    Year: 2011,
    Records: 2500000,
    "Organization type": "financial",
    "Method\r": "inside job\r",
  },
  {
    Index: 122,
    Entity: "Funimation",
    Year: 2016,
    Records: 2500000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 267,
    Entity: "Syrian government (Syria Files)",
    Year: 2012,
    Records: 2434899,
    "Organization type": "government",
    "Method\r": "hacked\r",
  },
  {
    Index: 18,
    Entity: "AOL",
    Year: 2014,
    Records: 2400000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 38,
    Entity: "Betfair",
    Year: 2010,
    Records: 2300000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 222,
    Entity: "Patreon",
    Year: 2015,
    Records: 2300000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 0,
    Entity: "21st Century Oncology",
    Year: 2016,
    Records: 2200000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 307,
    Entity: "University of Utah Hospital & Clinics",
    Year: 2008,
    Records: 2200000,
    "Organization type": "academic",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 306,
    Entity: "University of Miami",
    Year: 2008,
    Records: 2100000,
    "Organization type": "academic",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 96,
    Entity:
      "Earl Enterprises(Buca di Beppo, Earl of Sandwich, Planet Hollywood,Chicken Guy, Mixology, Tequila Taqueria)",
    Year: "2018-2019",
    Records: 2000000,
    "Organization type": "restaurant",
    "Method\r": "hacked\r",
  },
  {
    Index: 295,
    Entity: "Ubuntu",
    Year: 2013,
    Records: 2000000,
    "Organization type": "tech",
    "Method\r": "hacked\r",
  },
  {
    Index: 326,
    Entity: "Vodafone",
    Year: 2013,
    Records: 2000000,
    "Organization type": "telecoms",
    "Method\r": "inside job\r",
  },
  {
    Index: 35,
    Entity: "Bell Canada",
    Year: 2017,
    Records: 1900000,
    "Organization type": "telecoms",
    "Method\r": "poor security\r",
  },
  {
    Index: 138,
    Entity: "Health Net — IBM",
    Year: 2011,
    Records: 1900000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 205,
    Entity: "New York State Electric & Gas",
    Year: 2012,
    Records: 1800000,
    "Organization type": "energy",
    "Method\r": "inside job\r",
  },
  {
    Index: 204,
    Entity: "New York City Health & Hospitals Corp.",
    Year: 2010,
    Records: 1700000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 298,
    Entity: "UK Ministry of Defence",
    Year: 2008,
    Records: 1700000,
    "Organization type": "government",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 195,
    Entity: "Morinaga Confectionery",
    Year: 2022,
    Records: 1648922,
    "Organization type": "online shopping",
    "Method\r": "ransomware hacked\r",
  },
  {
    Index: 156,
    Entity: "Jefferson County, West Virginia",
    Year: 2008,
    Records: 1600000,
    "Organization type": "government",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 193,
    Entity: "Monster.com",
    Year: 2007,
    Records: 1600000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 200,
    Entity: "NEC Networks, LLC",
    Year: 2021,
    Records: 1600000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 113,
    Entity: "Facebook",
    Year: 2019,
    Records: 1500000,
    "Organization type": "social network",
    "Method\r": "accidentally uploaded\r",
  },
  {
    Index: 127,
    Entity: "Gawker",
    Year: 2010,
    Records: 1500000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 162,
    Entity: "KM.RU",
    Year: 2016,
    Records: 1500000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 212,
    Entity: "Nival Networks",
    Year: 2016,
    Records: 1500000,
    "Organization type": "gaming",
    "Method\r": "hacked\r",
  },
  {
    Index: 231,
    Entity: "RBS Worldpay",
    Year: 2008,
    Records: 1500000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 244,
    Entity: "SingHealth",
    Year: 2018,
    Records: 1500000,
    "Organization type": "government, database",
    "Method\r": "hacked\r",
  },
  {
    Index: 321,
    Entity: "Verizon Communications",
    Year: 2016,
    Records: 1500000,
    "Organization type": "telecoms",
    "Method\r": "hacked\r",
  },
  {
    Index: 91,
    Entity: "DSW Inc.",
    Year: 2005,
    Records: 1400000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 229,
    Entity: "Rakuten",
    Year: 2020,
    Records: 1381735,
    "Organization type": "web",
    "Method\r":
      'improper setting, hacked"\r\n148,Iberdrola,2022,1300000,energy,poor security\r\n328,Walmart,2015,1300000,retail,hacked\r\n241,Sega,2011,1290755,gaming,hacked\r\n329,Washington Post,2011,1270000,media,hacked\r\n154,Japan Pension Service,2015,1250000,special public corporation,hacked\r\n30,"AvMed, Inc.',
  },
  {
    Index: 33,
    Entity: "Bank of America",
    Year: 2005,
    Records: 1200000,
    "Organization type": "financial",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 300,
    Entity: "Universiti Teknologi MARA",
    Year: 2019,
    Records: 1164540,
    "Organization type": "academic",
    "Method\r": "hacked\r",
  },
  {
    Index: 77,
    Entity: "CyberServe",
    Year: 2021,
    Records: 1107034,
    "Organization type": "hosting provider",
    "Method\r": "hacked\r",
  },
  {
    Index: 55,
    Entity: "CareFirst BlueCross Blue Shield - Maryland",
    Year: 2015,
    Records: 1100000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 201,
    Entity: "Neiman Marcus",
    Year: 2014,
    Records: 1100000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 202,
    Entity: "Nemours Foundation",
    Year: 2011,
    Records: 1055489,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 44,
    Entity: "BlueCross BlueShield of Tennessee",
    Year: 2009,
    Records: 1023209,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 70,
    Entity: "Compass Bank",
    Year: 2007,
    Records: 1000000,
    "Organization type": "financial",
    "Method\r": "inside job\r",
  },
  {
    Index: 90,
    Entity: "Drupal",
    Year: 2013,
    Records: 1000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 93,
    Entity: "Dun & Bradstreet",
    Year: 2013,
    Records: 1000000,
    "Organization type": "tech",
    "Method\r": "hacked\r",
  },
  {
    Index: 165,
    Entity: "Kroll Background America",
    Year: 2013,
    Records: 1000000,
    "Organization type": "tech",
    "Method\r": "hacked\r",
  },
  {
    Index: 167,
    Entity: "LexisNexis",
    Year: 2014,
    Records: 1000000,
    "Organization type": "tech",
    "Method\r": "hacked\r",
  },
  {
    Index: 250,
    Entity: "Sony Pictures",
    Year: 2011,
    Records: 1000000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 189,
    Entity: "Mitsubishi Tokyo UFJ Bank",
    Year: 2006,
    Records: 960000,
    "Organization type": "financial",
    "Method\r": "intentionally lost\r",
  },
  {
    Index: 264,
    Entity: "Stratfor",
    Year: 2011,
    Records: 935000,
    "Organization type": "military",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 323,
    Entity: "Virgin Media",
    Year: 2020,
    Records: 900000,
    "Organization type": "mobile carrier",
    "Method\r": "accidentally exposed\r",
  },
  {
    Index: 219,
    Entity: "Orbitz",
    Year: 2018,
    Records: 880000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 174,
    Entity: "MacRumors.com",
    Year: 2014,
    Records: 860000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 139,
    Entity: "Health Sciences Authority (Singapore)",
    Year: 2019,
    Records: 808000,
    "Organization type": "healthcare",
    "Method\r": "poor security\r",
  },
  {
    Index: 49,
    Entity: "California Department of Child Support Services",
    Year: 2012,
    Records: 800000,
    "Organization type": "government",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 126,
    Entity: "Gap Inc.",
    Year: 2007,
    Records: 800000,
    "Organization type": "retail",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 255,
    Entity: "South Shore Hospital, Massachusetts",
    Year: 2010,
    Records: 800000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 180,
    Entity: "US Medicaid",
    Year: 2012,
    Records: 780000,
    "Organization type": "government, healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 218,
    Entity: "Ohio State University",
    Year: 2010,
    Records: 760000,
    "Organization type": "academic",
    "Method\r": "hacked\r",
  },
  {
    Index: 150,
    Entity: "Internal Revenue Service",
    Year: 2015,
    Records: 720000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 236,
    Entity: "Sakai City, Japan",
    Year: 2015,
    Records: 680000,
    "Organization type": "government",
    "Method\r": "inside job\r",
  },
  {
    Index: 86,
    Entity: "Domino's Pizza (France)",
    Year: 2014,
    Records: 600000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 203,
    Entity: "Network Solutions",
    Year: 2009,
    Records: 573000,
    "Organization type": "tech",
    "Method\r": "hacked\r",
  },
  {
    Index: 325,
    Entity: "Virginia Prescription Monitoring Program",
    Year: 2009,
    Records: 531400,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 151,
    Entity: "International Committee of the Red Cross",
    Year: 2022,
    Records: 515000,
    "Organization type": "humanitarian",
    "Method\r": "unknown\r",
  },
  {
    Index: 226,
    Entity: "Puerto Rico Department of Health",
    Year: 2010,
    Records: 515000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 98,
    Entity: "Eisenhower Medical Center",
    Year: 2011,
    Records: 514330,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 155,
    Entity: "Japanet Takata",
    Year: 2004,
    Records: 510000,
    "Organization type": "shopping",
    "Method\r": "inside job\r",
  },
  {
    Index: 46,
    Entity: "2018 British Airways cyberattack",
    Year: 2018,
    Records: 500000,
    "Organization type": "transport",
    "Method\r": "hacked\r",
  },
  {
    Index: 81,
    Entity: "Dedalus",
    Year: 2021,
    Records: 500000,
    "Organization type": "health",
    "Method\r": "poor security\r",
  },
  {
    Index: 130,
    Entity: "Google Plus",
    Year: 2018,
    Records: 500000,
    "Organization type": "social network",
    "Method\r": "poor security\r",
  },
  {
    Index: 137,
    Entity: "Health Net",
    Year: 2009,
    Records: 500000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 239,
    Entity: "Scribd",
    Year: 2013,
    Records: 500000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 245,
    Entity: "Slack",
    Year: 2015,
    Records: 500000,
    "Organization type": "tech",
    "Method\r": "poor security\r",
  },
  {
    Index: 115,
    Entity: "Fast Retailing",
    Year: 2019,
    Records: 461091,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 343,
    Entity: "Yahoo! Voices",
    Year: 2012,
    Records: 450000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 211,
    Entity: "Nippon Television",
    Year: 2016,
    Records: 430000,
    "Organization type": "media",
    "Method\r": "hacked\r",
  },
  {
    Index: 123,
    Entity: "Formspring",
    Year: 2012,
    Records: 420000,
    "Organization type": "web",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 116,
    Entity: "Federal Reserve Bank of Cleveland",
    Year: 2010,
    Records: 400000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 257,
    Entity: "Spartanburg Regional Healthcare System",
    Year: 2011,
    Records: 400000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 284,
    Entity: "Triple-S Salud, Inc.",
    Year: 2010,
    Records: 398000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 312,
    Entity: "U.S. Army(classified Iraq War documents)",
    Year: 2010,
    Records: 392000,
    "Organization type": "government",
    "Method\r": "inside job\r",
  },
  {
    Index: 349,
    Entity: "National Health Information Center (NCZI) of Slovakia",
    Year: 2020,
    Records: 391250,
    "Organization type": "healthcare",
    "Method\r": "poor security\r",
  },
  {
    Index: 169,
    Entity: "Les Éditions Protégez-vous",
    Year: 2020,
    Records: 380000,
    "Organization type": "publisher (magazine)",
    "Method\r": "unknown\r",
  },
  {
    Index: 246,
    Entity: "SlickWraps",
    Year: 2020,
    Records: 377428,
    "Organization type": "phone accessories",
    "Method\r": "poor security\r",
  },
  {
    Index: 144,
    Entity: "Hilton Hotels",
    Year: "2014 and 2015",
    Records: 363000,
    "Organization type": "hotel",
    "Method\r": "hacked\r",
  },
  {
    Index: 63,
    Entity: "Citigroup",
    Year: 2011,
    Records: 360083,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 51,
    Entity: "Capcom",
    Year: 2020,
    Records: 350000,
    "Organization type": "game",
    "Method\r": "hacked\r",
  },
  {
    Index: 7,
    Entity: "Affinity Health Plan, Inc.",
    Year: 2013,
    Records: 344579,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 102,
    Entity: "Emory Healthcare",
    Year: 2012,
    Records: 315000,
    "Organization type": "healthcare",
    "Method\r": "poor security\r",
  },
  {
    Index: 12,
    Entity: "Ancestry.com",
    Year: 2021,
    Records: 300000,
    "Organization type": "web",
    "Method\r": "poor security\r",
  },
  {
    Index: 256,
    Entity: "Southern California Medical-Legal Consultants",
    Year: 2011,
    Records: 300000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 304,
    Entity: "University of Maryland, College Park",
    Year: 2014,
    Records: 300000,
    "Organization type": "academic",
    "Method\r": "hacked\r",
  },
  {
    Index: 146,
    Entity: "Honda Canada",
    Year: 2011,
    Records: 283000,
    "Organization type": "retail",
    "Method\r": "poor security\r",
  },
  {
    Index: 20,
    Entity: "Apple",
    Year: 2021,
    Records: 275000,
    "Organization type": "tech",
    "Method\r": "hacked\r",
  },
  {
    Index: 273,
    Entity: "TD Bank",
    Year: 2012,
    Records: 260000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 318,
    Entity: "U.S. government (United States diplomatic cables leak)",
    Year: 2010,
    Records: 260000,
    "Organization type": "military",
    "Method\r": "inside job\r",
  },
  {
    Index: 100,
    Entity: "Embassy Cables",
    Year: 2010,
    Records: 251000,
    "Organization type": "government",
    "Method\r": "inside job\r",
  },
  {
    Index: 31,
    Entity: "Bailey's Inc.",
    Year: 2015,
    Records: 250000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 290,
    Entity: "Twitter",
    Year: 2013,
    Records: 250000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 209,
    Entity: "Nintendo (Club Nintendo)",
    Year: 2013,
    Records: 240000,
    "Organization type": "gaming",
    "Method\r": "hacked\r",
  },
  {
    Index: 240,
    Entity: "Seacoast Radiology, PA",
    Year: 2010,
    Records: 231400,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 178,
    Entity: "Massachusetts Government",
    Year: 2011,
    Records: 210000,
    "Organization type": "government",
    "Method\r": "poor security\r",
  },
  {
    Index: 11,
    Entity: "TD Ameritrade",
    Year: 2005,
    Records: 200000,
    "Organization type": "financial",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 39,
    Entity: "Bethesda Game Studios",
    Year: 2011,
    Records: 200000,
    "Organization type": "gaming",
    "Method\r": "hacked\r",
  },
  {
    Index: 143,
    Entity: "Hewlett Packard",
    Year: 2006,
    Records: 200000,
    "Organization type": "tech, retail",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 233,
    Entity: "Restaurant Depot",
    Year: 2011,
    Records: 200000,
    "Organization type": "retail",
    "Method\r": "hacked\r",
  },
  {
    Index: 101,
    Entity: "Emergency Healthcare Physicians, Ltd.",
    Year: 2010,
    Records: 180111,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 237,
    Entity: "San Francisco Public Utilities Commission",
    Year: 2011,
    Records: 180000,
    "Organization type": "government",
    "Method\r": "hacked\r",
  },
  {
    Index: 2,
    Entity: "Accendo Insurance Co.",
    Year: 2020,
    Records: 175350,
    "Organization type": "healthcare",
    "Method\r": "poor security\r",
  },
  {
    Index: 274,
    Entity: "TerraCom & YourTel",
    Year: 2013,
    Records: 170000,
    "Organization type": "telecoms",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 186,
    Entity: "Militarysingles.com",
    Year: 2012,
    Records: 163792,
    "Organization type": "web, military",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 65,
    Entity: "City and Hackney Teaching Primary Care Trust",
    Year: 2007,
    Records: 160000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 210,
    Entity: "Nintendo (Nintendo Account)",
    Year: 2020,
    Records: 160000,
    "Organization type": "gaming",
    "Method\r": "hacked\r",
  },
  {
    Index: 302,
    Entity: "University of California, Berkeley",
    Year: 2009,
    Records: 160000,
    "Organization type": "academic",
    "Method\r": "hacked\r",
  },
  {
    Index: 330,
    Entity: "Washington State court system",
    Year: 2013,
    Records: 160000,
    "Organization type": "government",
    "Method\r": "hacked\r",
  },
  {
    Index: 14,
    Entity: "Ankle & Foot Center of Tampa Bay, Inc.",
    Year: 2021,
    Records: 156000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 64,
    Entity: "Citigroup",
    Year: 2013,
    Records: 150000,
    "Organization type": "financial",
    "Method\r": "poor security\r",
  },
  {
    Index: 319,
    Entity: "National Guard of the United States",
    Year: 2009,
    Records: 131000,
    "Organization type": "military",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 171,
    Entity: "Lincoln Medical & Mental Health Center",
    Year: 2010,
    Records: 130495,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 320,
    Entity: "Vastaamo",
    Year: 2020,
    Records: 130000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 29,
    Entity: "Automatic Data Processing",
    Year: 2005,
    Records: 125000,
    "Organization type": "financial",
    "Method\r": "poor security\r",
  },
  {
    Index: 161,
    Entity: "Kirkwood Community College",
    Year: 2013,
    Records: 125000,
    "Organization type": "academic",
    "Method\r": "hacked\r",
  },
  {
    Index: 224,
    Entity: "Popsugar",
    Year: 2018,
    Records: 123857,
    "Organization type": "fashion",
    "Method\r": "hacked\r",
  },
  {
    Index: 316,
    Entity: "U.S. law enforcement (70 different agencies)",
    Year: 2011,
    Records: 123461,
    "Organization type": "government",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 24,
    Entity: "AT&T",
    Year: 2010,
    Records: 114000,
    "Organization type": "telecoms",
    "Method\r": "hacked\r",
  },
  {
    Index: 23,
    Entity: "AT&T",
    Year: 2008,
    Records: 113000,
    "Organization type": "telecoms",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 57,
    Entity: "Central Hudson Gas & Electric",
    Year: 2013,
    Records: 110000,
    "Organization type": "energy",
    "Method\r": "hacked\r",
  },
  {
    Index: 67,
    Entity: "Colorado government",
    Year: 2010,
    Records: 105470,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 182,
    Entity: "Memorial Healthcare System",
    Year: 2011,
    Records: 102153,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 36,
    Entity: "Bell Canada",
    Year: 2018,
    Records: 100000,
    "Organization type": "telecoms",
    "Method\r": "hacked\r",
  },
  {
    Index: 75,
    Entity: "Crescent Health Inc., Walgreens",
    Year: 2013,
    Records: 100000,
    "Organization type": "healthcare",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 120,
    Entity: "Florida Department of Juvenile Justice",
    Year: 2013,
    Records: 100000,
    "Organization type": "government",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 335,
    Entity: "Westpac",
    Year: 2019,
    Records: 98000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 259,
    Entity: "Starbucks",
    Year: 2008,
    Records: 97000,
    "Organization type": "retail",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 351,
    Entity: "IKEA",
    Year: 2022,
    Records: 95000,
    "Organization type": "retail",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 21,
    Entity: "Apple Health Medicaid",
    Year: 2021,
    Records: 91000,
    "Organization type": "healthcare",
    "Method\r": "poor security\r",
  },
  {
    Index: 45,
    Entity: "BMO and Simplii",
    Year: 2018,
    Records: 90000,
    "Organization type": "banking",
    "Method\r": "poor security\r",
  },
  {
    Index: 276,
    Entity: "Texas Lottery",
    Year: 2007,
    Records: 89000,
    "Organization type": "government",
    "Method\r": "inside job\r",
  },
  {
    Index: 297,
    Entity: "UK Home Office",
    Year: 2008,
    Records: 84000,
    "Organization type": "government",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 303,
    Entity: "University of California, Berkeley",
    Year: 2016,
    Records: 80000,
    "Organization type": "academic",
    "Method\r": "hacked\r",
  },
  {
    Index: 196,
    Entity: "Mozilla",
    Year: 2014,
    Records: 76000,
    "Organization type": "web",
    "Method\r": "poor security\r",
  },
  {
    Index: 6,
    Entity: "AerServ (subsidiary of InMobi)",
    Year: 2018,
    Records: 75000,
    "Organization type": "advertising",
    "Method\r": "hacked\r",
  },
  {
    Index: 73,
    Entity: "Centers for Medicare & Medicaid Services",
    Year: 2018,
    Records: 75000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 308,
    Entity: "University of Wisconsin–Milwaukee",
    Year: 2011,
    Records: 73000,
    "Organization type": "academic",
    "Method\r": "hacked\r",
  },
  {
    Index: 258,
    Entity: "Stanford University",
    Year: 2008,
    Records: 72000,
    "Organization type": "academic",
    "Method\r": "lost / stolen computer\r",
  },
  {
    Index: 313,
    Entity: "U.S. Department of Defense",
    Year: 2009,
    Records: 72000,
    "Organization type": "military",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 305,
    Entity: "University of Central Florida",
    Year: 2016,
    Records: 63000,
    "Organization type": "academic",
    "Method\r": "hacked\r",
  },
  {
    Index: 338,
    Entity: "Writerspace.com",
    Year: 2011,
    Records: 62000,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 56,
    Entity: "Central Coast Credit Union",
    Year: 2016,
    Records: 60000,
    "Organization type": "financial",
    "Method\r": "hacked\r",
  },
  {
    Index: 206,
    Entity: "New York Taxis",
    Year: 2014,
    Records: 52000,
    "Organization type": "transport",
    "Method\r": "poor security\r",
  },
  {
    Index: 242,
    Entity: "Service Personnel and Veterans Agency (UK)",
    Year: 2008,
    Records: 50500,
    "Organization type": "government",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 292,
    Entity: "Uber",
    Year: 2014,
    Records: 50000,
    "Organization type": "tech",
    "Method\r": "poor security\r",
  },
  {
    Index: 311,
    Entity: "U.S. Army",
    Year: 2011,
    Records: 50000,
    "Organization type": "military",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 344,
    Entity: "Yale University",
    Year: 2010,
    Records: 43000,
    "Organization type": "academic",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 74,
    Entity: "Cox Communications",
    Year: 2016,
    Records: 40000,
    "Organization type": "telecoms",
    "Method\r": "hacked\r",
  },
  {
    Index: 194,
    Entity: "Morgan Stanley Smith Barney",
    Year: 2011,
    Records: 34000,
    "Organization type": "financial",
    "Method\r": "lost / stolen media\r",
  },
  {
    Index: 84,
    Entity: "US Department of Homeland Security",
    Year: 2016,
    Records: 30000,
    "Organization type": "government",
    "Method\r": "poor security\r",
  },
  {
    Index: 214,
    Entity: "Now:Pensions",
    Year: 2020,
    Records: 30000,
    "Organization type": "financial",
    "Method\r": "rogue contractor\r",
  },
  {
    Index: 132,
    Entity: "Grozio Chirurgija",
    Year: 2017,
    Records: 25000,
    "Organization type": "healthcare",
    "Method\r": "hacked\r",
  },
  {
    Index: 9,
    Entity: "Air Canada",
    Year: 2018,
    Records: 20000,
    "Organization type": "transport",
    "Method\r": "hacked\r",
  },
  {
    Index: 83,
    Entity: "Democratic National Committee",
    Year: 2016,
    Records: 19252,
    "Organization type": "political",
    "Method\r": "\r",
  },
  {
    Index: 253,
    Entity: "South Africa police",
    Year: 2013,
    Records: 16000,
    "Organization type": "government",
    "Method\r": "hacked\r",
  },
  {
    Index: 188,
    Entity: "Ministry of Health (Singapore)",
    Year: 2019,
    Records: 14200,
    "Organization type": "healthcare",
    "Method\r": "poor security/inside job\r",
  },
  {
    Index: 271,
    Entity: "TaxSlayer.com",
    Year: 2016,
    Records: 8800,
    "Organization type": "web",
    "Method\r": "hacked\r",
  },
  {
    Index: 152,
    Entity: "Inuvik hospital",
    Year: 2016,
    Records: 6700,
    "Organization type": "healthcare",
    "Method\r": "inside job\r",
  },
  {
    Index: 40,
    Entity: "Bethesda Game Studios",
    Year: 2018,
    Records: "",
    "Organization type": "gaming",
    "Method\r": "accidentally published\r",
  },
  {
    Index: 337,
    Entity: "WordPress",
    Year: 2018,
    Records: "",
    "Organization type": "web service",
    "Method\r": "hacked",
  },
];

function DataBreachesAreaChart() {
  return (
    <div className="col d-flex">
      <div style={{ width: "90%" }}>
        <h1 style={{ textAlign: "center" }}>
          Data Breaches Worldwide - Area Chart
        </h1>
        <div className="col d-flex justify-content-center">
          <ResponsiveContainer width="90%" height={500}>
            <AreaChart
              width={500}
              height={1000}
              data={data}
              syncId="anyId"
              margin={{
                top: 10,
                right: 30,
                left: 0,
                bottom: 0,
              }}
            >
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="Entity" />
              <YAxis />
              <Tooltip />
              <Area
                type="monotone"
                dataKey="Records"
                stroke="#8884d8"
                fill="#8884d8"
              />
            </AreaChart>
          </ResponsiveContainer>
        </div>
        <p>Maybe some other content</p>
      </div>
    </div>
  );
}

export default DataBreachesAreaChart;
